version: '2'

services:
  database:
    extends:
      file: services/database.yml
      service: database
    ports:
      - "37017:27017"
  fee-service:
    extends:
      file: services/fee-service.yml
      service: fee-service
    ports:
      - "8090:8090"

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.25.0/24
          iprange: 192.168.25.0/25
          gateway: 192.168.25.1

