version: '2'

services:
  database:
    image: mongo:3.2.4
    container_name: mongo-fee-service
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
